FROM python:3.10.6

RUN apt-get update \
  && apt-get install -y --no-install-recommends --no-install-suggests \
  && pip install --no-cache-dir --upgrade pip

WORKDIR /api_application

COPY docker-require.txt /api_application
RUN pip install --no-cache-dir -r /api_application/docker-require.txt

COPY . /api_application

RUN chmod +x api_application/trigger.py

EXPOSE 8080

CMD ["python", "api_application/trigger.py"]
