FROM python:3.10.6

RUN apt-get update \
  && apt-get install -y --no-install-recommends --no-install-suggests \
  && pip install --no-cache-dir --upgrade pip

WORKDIR /scraper_application

COPY docker-require-scrape.txt /scraper_application
RUN pip install --no-cache-dir -r /scraper_application/docker-require-scrape.txt

COPY . /scraper_application

RUN chmod +x scraper_application/trigger.py

EXPOSE 8080

CMD ["python", "scraper_application/trigger.py"]
