FROM python:3.10.6

RUN apt-get update \
  && apt-get install -y --no-install-recommends --no-install-suggests \
  && pip install --no-cache-dir --upgrade pip

WORKDIR /historical_application

COPY docker-require-hist.txt /historical_application
RUN pip install --no-cache-dir -r /historical_application/docker-require-hist.txt

COPY . /historical_application

RUN chmod +x historical_application/trigger.py

EXPOSE 8080

CMD ["python", "historical_application/trigger.py"]
