FROM python:3.10.6

RUN apt-get update \
  && apt-get install -y --no-install-recommends --no-install-suggests \
  && pip install --no-cache-dir --upgrade pip

WORKDIR /monolith

COPY ../monolith /monolith

RUN pip install --no-cache-dir -r /monolith/requirements.txt

EXPOSE 8080

CMD ["python", "trigger.py"]
